<a href="https://colab.research.google.com/github/WandersonGustavo/Udemy_Data_Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

*TESTE*

In [ ]:
data=[10,4.5,8.1,9,7]
array=np.array(data)
array

array([10. ,  4.5,  8.1,  9. ,  7. ])

In [ ]:
data2=[[1,2,3,4,5],[6,7,8,9,10]]
array2=np.array(data2)
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
array2.ndim

2

In [ ]:
array2.shape

(2, 5)

In [ ]:
array.shape

(5,)

In [ ]:
array.size

5

In [ ]:
array.itemsize

8

In [ ]:
array.ndim

1

In [ ]:
1/array

array([0.1       , 0.22222222, 0.12345679, 0.11111111, 0.14285714])

In [ ]:
array.dot(array)

315.86

In [ ]:
array.astype(np.int32)

array([10,  4,  8,  9,  7], dtype=int32)

In [ ]:
r = np.random.rand(3, 3)
r

array([[0.98885452, 0.00671013, 0.60694694],
       [0.72450277, 0.52006335, 0.16143731],
       [0.96119056, 0.59723861, 0.37584569]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Indexação e fatiamento: modos com os quais você pode querer selecionar um subconjunto de seus dados**

In [ ]:
array = np.arange(10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array[5]

5

In [ ]:
array[2:6]

array([2, 3, 4, 5])

In [ ]:
array[-1]

9

In [ ]:
array[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array[::2]

array([0, 2, 4, 6, 8])

In [ ]:
array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
X = np.arange(1000).reshape((10,100)) 
#X[0:4,7:10]


In [ ]:
X[np.array([3,4])]

array([[300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
        313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
        326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
        339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
        352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,
        365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377,
        378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390,
        391, 392, 393, 394, 395, 396, 397, 398, 399],
       [400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
        413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
        426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
        439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
        452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
        465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 47

In [ ]:
X[np.array([3,4]), np.array([11,12]) ] 

array([311, 412])

In [ ]:
cubo = np.array([[[1,4,7],[3,5,2]],[[5,6,0],[7,4,1]],[[2,8,8],[0,3,6]]])
print('Array tridimensional:\n ', cubo)


Array tridimensional:
  [[[1 4 7]
  [3 5 2]]

 [[5 6 0]
  [7 4 1]]

 [[2 8 8]
  [0 3 6]]]


In [ ]:
y =  np.array([[1,2,3,4],[12,45,88,54]])
y

array([[ 1,  2,  3,  4],
       [12, 45, 88, 54]])

In [ ]:
y.shape

(2, 4)

In [ ]:
np.transpose(y)

array([[ 1, 12],
       [ 2, 45],
       [ 3, 88],
       [ 4, 54]])

In [ ]:
y.flatten()

array([ 1,  2,  3,  4, 12, 45, 88, 54])

In [ ]:
y.reshape(2,4)

array([[ 1,  2,  3,  4],
       [12, 45, 88, 54]])

In [ ]:
a = np.array([1,2,3])
b = np.array([1,4,3])
a==b

array([ True, False,  True])

In [ ]:
np.greater(a,b)

array([False, False, False])

In [ ]:
import numpy as np 
       
# 2D   
arr = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4,]]  
   
print("\nSoma do array : ", np.sum(arr)) 
print("Soma do array(axis = 0) : ", np.sum(arr, axis = 0)) 
#print("Soma do array(axis = 1) : ", np.sum(arr, axis = 1))
  
print("\nSoma do array (keepdims is True): \n",
      np.sum(arr, axis = 0, keepdims = True))


Soma do array :  279
Soma do array(axis = 0) :  [52 25 93 42 67]

Soma do array (keepdims is True): 
 [[52 25 93 42 67]]
